version: '3.8'

services:
  web:
    build: ./services/server
    command: python app.py
    volumes:
      - ./services/server:/app
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  celery_worker:
    build: ./services/server
    image: celery_worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./services/server:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  celery_beat:
    build: ./services/server
    image: celery_beat
    command: rm -f './celerybeat.pid' && celery -A app.celery beat -l info
    volumes:
      - ./services/server:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  flower:
    build: ./services/server
    image: celery_flower
    command: celery -A app.celery --broker="redis://redis:6379/0" flower
    volumes:
      - ./services/server:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${PS_DATABASE_NAME}
      POSTGRES_USER: ${PS_DATABASE_USER}
      POSTGRES_PASSWORD: ${PS_DATABASE_PASSWORD}
    ports:
      - 5432:5432

  nginx:
    image: nginx
    volumes:
     - ./services/nginx:/etc/nginx/templates
     - ./services/nginx/certs:/etc/nginx/certs
    ports:
     - "443:443"
     - "80:80"
    links:
     - web
    depends_on:
     - web
volumes:
  postgres_data: