version: '3.8'

services:
  postgres-test:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${PS_DATABASE_NAME}
      POSTGRES_PORT: 5433
      POSTGRES_USER: ${PS_DATABASE_USER}
      POSTGRES_PASSWORD: ${PS_DATABASE_PASSWORD}
    ports:
      - 5433:5433
    command: -p 5433

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  celery_worker:
    build: ./services/server
    image: celery_worker
    command: celery -A app.celery worker --loglevel=warning
    volumes:
      - ./services/server:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres